server:
  port: 5001
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
        namespace: public
    gateway:
      routes:
        - id: demo-service
          uri: lb://demo
          predicates:
            - Path=/demo/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comments/**
      discovery:
        locator:
          enabled: true
logging:
  level:
    root: debug